const productos = [
    {
      nombre: "Limpiador Multiusos",
      descripcion: "Limpiador multiusos para superficies",
      precio: 15.99,
      capacidad: 1.0,
      concentracion: "10%",
      categoriaId: 1,
      marcaId: 1,
      unidadId: 1,
      proveedorId: 1,
    },
    {
      nombre: "Desinfectante",
      descripcion: "Desinfectante para baños y cocinas",
      precio: 12.50,
      capacidad: 0.75,
      concentracion: "20%",
      categoriaId: 2,
      marcaId: 2,
      unidadId: 2,
      proveedorId: 2,
    },
    {
      nombre: "Detergente Líquido",
      descripcion: "Detergente líquido para ropa",
      precio: 8.99,
      capacidad: 1.5,
      concentracion: "30%",
      categoriaId: 3,
      marcaId: 3,
      unidadId: 3,
      proveedorId: 3,
    },
    {
      nombre: "Lavandina",
      descripcion: "Lavandina para desinfección",
      precio: 5.99,
      capacidad: 1.0,
      concentracion: "5%",
      categoriaId: 4,
      marcaId: 4,
      unidadId: 4,
      proveedorId: 4,
    },
    {
      nombre: "Jabón Líquido",
      descripcion: "Jabón líquido para manos",
      precio: 3.99,
      capacidad: 0.5,
      concentracion: "15%",
      categoriaId: 5,
      marcaId: 5,
      unidadId: 5,
      proveedorId: 5,
    },
    {
      nombre: "Suavizante",
      descripcion: "Suavizante para ropa",
      precio: 6.99,
      capacidad: 1.0,
      concentracion: "25%",
      categoriaId: 6,
      marcaId: 6,
      unidadId: 3,
      proveedorId: 6,
    },
    {
      nombre: "Limpiavidrios",
      descripcion: "Limpiavidrios para superficies de vidrio",
      precio: 4.99,
      capacidad: 0.75,
      concentracion: "10%",
      categoriaId: 7,
      marcaId: 7,
      unidadId: 2,
      proveedorId: 7,
    },
    {
      nombre: "Desengrasante",
      descripcion: "Desengrasante para cocina",
      precio: 7.99,
      capacidad: 1.0,
      concentracion: "20%",
      categoriaId: 8,
      marcaId: 8,
      unidadId: 1,
      proveedorId: 8,
    },
    {
      nombre: "Limpiador de Alfombras",
      descripcion: "Limpiador para alfombras y tapetes",
      precio: 9.99,
      capacidad: 1.5,
      concentracion: "30%",
      categoriaId: 9,
      marcaId: 9,
      unidadId: 3,
      proveedorId: 9,
    },
    {
      nombre: "Desodorante de Piso",
      descripcion: "Desodorante para pisos",
      precio: 5.50,
      capacidad: 1.0,
      concentracion: "10%",
      categoriaId: 8,
      marcaId: 8,
      unidadId: 3,
      proveedorId: 8,
    }
  ];
  
  export default productos;