const productos = [
    {
      nombre: "Limpiador multiusos para superficies",
      precio: 15.99,
      capacidad: 1.0,
      stock:5,
      categoriaId: 1,
      marcaId: 1,
      unidadId: 1,
      proveedorId: 1,
    },
    {
      nombre: "Desinfectante para baños y cocinas",
      precio: 12.50,
      capacidad: 0.75,
      stock:14,
      categoriaId: 2,
      marcaId: 2,
      unidadId: 2,
      proveedorId: 2,
    },
    {
      nombre: "Detergente líquido para ropa",
      precio: 8.99,
      capacidad: 1.5,
      stock:7,
      categoriaId: 3,
      marcaId: 3,
      unidadId: 3,
      proveedorId: 3,
    },
    {
      nombre: "Lavandina para desinfección",
      precio: 5.99,
      capacidad: 1.0,
      stock:3,
      categoriaId: 4,
      marcaId: 4,
      unidadId: 4,
      proveedorId: 4,
    },
    {
      nombre: "Jabón líquido para manos",
      precio: 3.99,
      capacidad: 0.5,
      stock:8,
      categoriaId: 5,
      marcaId: 5,
      unidadId: 5,
      proveedorId: 5,
    },
    {
      nombre: "Suavizante para ropa",
      precio: 6.99,
      capacidad: 1.0,
      stock:9,
      categoriaId: 6,
      marcaId: 6,
      unidadId: 3,
      proveedorId: 6,
    },
    {
      nombre: "Limpiavidrios para superficies de vidrio",
      precio: 4.99,
      capacidad: 0.75,
      stock:10,
      categoriaId: 7,
      marcaId: 7,
      unidadId: 2,
      proveedorId: 7,
    },
    {
      nombre: "Desengrasante para cocina",
      precio: 7.99,
      capacidad: 1.0,
      stock:15,
      categoriaId: 8,
      marcaId: 8,
      unidadId: 1,
      proveedorId: 8,
    },
    {
      nombre: "Limpiador para alfombras y tapetes",
      precio: 9.99,
      capacidad: 1.5,
      stock:20,
      categoriaId: 9,
      marcaId: 9,
      unidadId: 3,
      proveedorId: 9,
    },
    {
      nombre: "Desodorante para pisos",
      precio: 5.50,
      capacidad: 1.0,
      stock:22,
      categoriaId: 8,
      marcaId: 8,
      unidadId: 3,
      proveedorId: 8,
    }
  ];
  
  export default productos;